---
- hosts: all
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: Copy httpd configuration file
      copy:
        src: /home/ubuntu/ansible/apache2.org
        dest: /etc/apache2/apache2.conf
    - name: Copy index file
      copy: src=/home/ubuntu/ansible/index.html dest=/var/www/html
      notify:
      - restart apache
    - name: start and enable httpd service
      service:
        name: apache2
        state: restarted
        enabled: yes
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
...
