---
- hosts: all
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      
    - name: Copy httpd configuration file
      copy: src:/data/httpd.original dest=/etc/httpd/conf/htttpd.conf

    - name: Copy index file 
      copy: src:/data/index.html dest=/var/www/html
      notify:
      - restart apache
      
    - name: start and enable httpd service 
      service: name: httpd state:restarted enabled=yes      
      
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
